- hosts: localhost
  connection: local
  gather_facts: true

  vars:
    # Пакеты из официальных репозиториев Arch/CachyOS
    pacman_packages:
      #- nvidia-dkms
      - docker
      - docker-compose
      - telegram-desktop
      - discord
      #- flameshot
      - gramps
      - libreoffice-fresh
      - qbittorrent
      - texmaker
      - thunderbird
      - firefox
      - virtualbox
      - virtualbox-host-dkms
      - vlc
      - ruff
      - neovim
      - yt-dlp
      - ttf-jetbrains-mono
      - github-cli
      - zed
      #- ghostty
      - btop
      - eza
      - fd
      - yazi
      - ffmpeg
      - jq
      - ripgrep
      - fzf
      - zoxide
      - nerd-fonts
      - procs
      - duf
      - dust
      - lazygit
      - graphviz
      - tree

    # Пакеты из AUR
    aur_packages:
      - lazydocker
      - lmstudio
      - obsidian
      - yandex-browser
      - warp-terminal
      - throne-bin
      - cursor-bin
      - slack-desktop
      - visual-studio-code-bin
      - zoom
      - peazip

  pre_tasks:
    - name: 👉 Принудительное обновление ключей CachyOS
      become: true
      pacman:
        name: cachyos-keyring
        state: latest

    - name: 👉 Обновление базы данных пакетов
      become: true
      pacman:
        update_cache: yes

  tasks:
    - name: 👉 Обновление всех пакетов системы
      become: true
      pacman:
        upgrade: yes

    - name: 👉 Установка 'base-devel' для сборки AUR пакетов
      become: true
      pacman:
        name: base-devel
        state: present

    - name: 👉 Установка yay (AUR-хелпер)
      kewlfft.aur.aur:
        name: yay
        state: present
      become: false

    - name: 👉 Установка пакетов из официальных репозиториев
      become: true
      pacman:
        name: "{{ pacman_packages }}"
        state: present

    - name: 👉 Установка пакетов из AUR
      kewlfft.aur.aur:
        use: yay
        name: "{{ aur_packages }}"
        state: present
      become: false

    - name: 👉 Настройка Docker
      become: true
      block:
        - name: Добавление пользователя в группу docker
          user:
            name: "{{ ansible_user_id }}"
            groups: docker
            append: yes

        - name: Включение и запуск Docker
          systemd:
            name: docker
            enabled: yes
            state: started

    - name: 👉 Установка Rust
      become: false
      become_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
      shell: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      args:
        creates: "{{ ansible_env.HOME }}/.cargo/bin/rustc"

    - name: 👉 Установка uv
      become: false
      become_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
      shell: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
      args:
        creates: "{{ ansible_env.HOME }}/.local/bin/uv"

    - name: 🔑 Установка JetBrains Toolbox
      tags: vpn
      kewlfft.aur.aur:
        use: yay
        name: jetbrains-toolbox
        state: present
      become: false

    - name: 🔑 Установка Julia
      tags: vpn
      become: false
      become_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
      shell: |
        curl -fsSL https://install.julialang.org | sh -s -- --yes

    - name: 👉 Добавить алиасы в fish
      blockinfile:
        path: "{{ ansible_env.HOME }}/.config/fish/config.fish"
        marker: '##### {mark} ALIASES #####'
        block: |
          alias ls 'eza -lhoUm --icons --hyperlink --time-style iso --colour-scale=age --no-permissions'
          alias lsg 'eza -lhoUm --icons --hyperlink --time-style iso --colour-scale=age --no-permissions --git --git-repos'
          alias ll 'eza -lhagoUm --icons --hyperlink --time-style iso --colour-scale=age --smart-group'
          alias llg 'eza -lhagoUm --icons --hyperlink --time-style iso --colour-scale=age --smart-group --git --git-repos'
          alias lls 'eza -lhagoUm --icons --hyperlink --time-style iso --colour-scale=age --smart-group --total-size'
          alias as-tree 'tree --fromfile' # показать дерево, пример: fd -e rs | as-tree
          alias fda 'fd -u' # поиск включает скрытые и игнорируемые
          alias smi 'watch -n 1 -d nvidia-smi'
          alias fzf 'fzf --height 50% --layout reverse --info inline --border'
          alias fzfp "fzf --height 50% --layout reverse --info inline --border --preview 'batcat --color=always {}' --preview-window '~3'"
          alias ps 'procs --watch'
          alias pst 'procs --tree'
          alias psc 'procs --watch --sortd cpu'
          alias psm 'procs --watch --sortd mem'
          alias lzg 'lazygit'
          alias lzd 'lazydocker'

    - name: 👉 Добавление интеграций в fish
      blockinfile:
        path: "{{ ansible_env.HOME }}/.config/fish/config.fish"
        marker: '##### {mark} INTEGRATIONS #####'
        block: |
          fzf --fish | source
          zoxide init fish | source
          source <(procs --gen-completion-out fish)
          abbr -a --position anywhere -- --help '--help | bat -plhelp'
          abbr -a --position anywhere -- -h '-h | bat -plhelp'

    - name: 👉 Обновление автодополнений для fish
      become: false
      become_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
      shell: fish -c 'fish_update_completions'

    - name: 👉 Обновление базы tldr
      become: false
      become_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
      shell: fish -c 'tldr --update'

    - name: 👉 Отключение KDE Wallet
      ini_file:
        path: "{{ ansible_env.HOME }}/.config/kwalletrc"
        create: yes
        section: Wallet
        option: Enabled
        value: 'false'
        mode: '0644'
      become: false
      become_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"

    - name: 👉 Переназначение горячих клавиш для Spectacle
      blockinfile:
        path: "{{ ansible_env.HOME }}/.config/kglobalshortcutsrc"
        marker: "##### {mark} SPECTACLE SHORTCUTS #####"
        block: |
          [services][org.kde.spectacle.desktop]
          RectangularRegionScreenShot=Print
          _launch=Meta+Shift+Print\tMeta+Shift+S

    - name: 👉 Копирование .config
      copy:
        src: "{{ playbook_dir }}/.config/"
        dest: "{{ ansible_env.HOME }}/.config/"
        mode: "0644"
        directory_mode: "0755"

    - name: Информационное сообщение
      debug:
        msg: |
          ========================================================================
          ✅ Установка завершена!

          ℹ️ ВАЖНО: Чтобы изменения для Docker, NVIDIA, Julia и VirtualBox
          вступили в силу, необходимо перезагрузить компьютер.

          Для VirtualBox может понадобиться:
          sudo modprobe vboxdrv
          ========================================================================
