- hosts: localhost
  connection: local
  gather_facts: true

  vars:
    # Пакеты из официальных репозиториев Arch/CachyOS
    pacman_packages:
      - docker
      - docker-compose
      - docker-buildx
      - telegram-desktop
      - discord
      - gramps
      - libreoffice-fresh
      - qbittorrent
      - thunderbird
      - firefox
      - virtualbox
      - virtualbox-host-dkms
      - virtualbox-guest-iso
      - vlc
      - vlc-plugins-all
      - vlc-gui-skins2
      - ruff
      - uv
      - ty
      - helix
      - yt-dlp
      - ttf-jetbrains-mono
      - github-cli
      - zed
      - ghostty
      - btop
      - eza
      - fd
      - yazi
      - ffmpeg
      - jq
      - ripgrep
      - fzf
      - zoxide
      - nerd-fonts
      - procs
      - duf
      - dust
      - lazygit
      - graphviz
      - tree
      - broot
      - okular
      - texlive-basic
      - texlive-latex
      - texlive-latexrecommended
      - texlive-latexextra
      - texlive-fontsrecommended
      - texlive-fontsextra
      - texlive-langcyrillic
      - texlive-langenglish
      - texlive-mathscience
      - texmaker
      - handbrake
      - kdenlive
      - kompare
      - kdiff3
      - difftastic
      - nvtop
      - openai-codex
      - ollama-cuda

    # Пакеты из AUR
    aur_packages:
      - lazydocker
      - lmstudio-bin
      - obsidian
      - yandex-browser
      - warp-terminal
      #- throne-bin
      - cursor-bin
      - slack-desktop
      - visual-studio-code-bin
      - zoom
      - peazip
      - nvidia-container-toolkit
      - amneziavpn-bin
      - google-chrome
      - wtfutil
      - opencode-bin
      - tradingview

  pre_tasks:
    - name: 👉 Принудительное обновление ключей CachyOS
      become: true
      pacman:
        name: cachyos-keyring
        state: latest

    - name: 👉 Обновление базы данных пакетов
      become: true
      pacman:
        update_cache: yes

  tasks:
    - name: 👉 Обновление всех пакетов системы
      become: true
      pacman:
        upgrade: yes

    - name: 👉 Установка 'base-devel' для сборки AUR пакетов
      become: true
      pacman:
        name: base-devel
        state: present

    - name: 👉 Установка пакетов из официальных репозиториев
      become: true
      pacman:
        name: "{{ pacman_packages }}"
        state: present

    - name: 👉 Установка пакетов из AUR
      kewlfft.aur.aur:
        use: paru
        name: "{{ aur_packages }}"
        state: present
      become: false

    - name: 👉 Настройка Docker
      become: true
      block:
        - name: Добавление пользователя в группу docker
          user:
            name: "{{ ansible_user_id }}"
            groups: docker
            append: yes

        - name: Включение и запуск Docker
          systemd:
            name: docker
            enabled: yes
            state: started

    - name: 👉 Настройки git
      become: false
      become_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
      shell: |
        git config --global core.quotepath false
        
    - name: 👉 Установка Rust
      become: false
      become_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
      shell: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      args:
        creates: "{{ ansible_env.HOME }}/.cargo/bin/rustc"

    - name: 👉 Добавление автодополнений для uv
      become: false
      become_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
      shell: |
        echo 'uv generate-shell-completion fish | source' > ~/.config/fish/completions/uv.fish
        echo 'uvx --generate-shell-completion fish | source' > ~/.config/fish/completions/uvx.fish

    - name: 🔑 Установка JetBrains Toolbox
      tags: vpn
      kewlfft.aur.aur:
        use: paru
        name: jetbrains-toolbox
        state: present
      become: false

    - name: 🔑 Установка Julia
      tags: vpn
      become: false
      become_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
      shell: |
        curl -fsSL https://install.julialang.org | sh -s -- --yes

    - name: 👉 Добавить алиасы в fish
      blockinfile:
        path: "{{ ansible_env.HOME }}/.config/fish/config.fish"
        marker: '##### {mark} ALIASES #####'
        block: |
          alias ls 'eza -lhoUm --icons --hyperlink --time-style iso --colour-scale=age --no-permissions'
          alias lsg 'eza -lhoUm --icons --hyperlink --time-style iso --colour-scale=age --no-permissions --git --git-repos'
          alias ll 'eza -lhagoUm --icons --hyperlink --time-style iso --colour-scale=age --smart-group'
          alias llg 'eza -lhagoUm --icons --hyperlink --time-style iso --colour-scale=age --smart-group --git --git-repos'
          alias lls 'eza -lhagoUm --icons --hyperlink --time-style iso --colour-scale=age --smart-group --total-size'
          alias as-tree 'tree --fromfile' # показать дерево, пример: fd -e rs | as-tree
          alias fda 'fd -u' # поиск включает скрытые и игнорируемые
          alias smi 'watch -n 1 -d nvidia-smi'
          alias fzf 'fzf --height 50% --layout reverse --info inline --border'
          alias fzfp "fzf --height 50% --layout reverse --info inline --border --preview 'bat --color=always {}' --preview-window '~3'"
          alias ps 'procs --watch'
          alias pst 'procs --tree'
          alias psc 'procs --watch --sortd cpu'
          alias psm 'procs --watch --sortd mem'
          alias lzg 'lazygit'
          alias lzd 'lazydocker'
          alias system_update 'paru;rustup self update;rustup update;juliaup self update;juliaup update'
          alias system_clean 'paru -Sc;paru -c'
          alias clearml_run 'docker compose -f /opt/clearml/docker-compose.yml up -d;echo The server is now running on http://localhost:8080/projects'
          alias clearml_stop 'docker compose -f /opt/clearml/docker-compose.yml down'
          alias clearml_update 'sudo curl https://raw.githubusercontent.com/clearml/clearml-server/master/docker/docker-compose.yml -o /opt/clearml/docker-compose.yml;docker compose -f /opt/clearml/docker-compose.yml pull'
          alias hx 'helix'
          alias wtf 'wtfutil'

    - name: 👉 Добавление интеграций в fish
      blockinfile:
        path: "{{ ansible_env.HOME }}/.config/fish/config.fish"
        marker: '##### {mark} INTEGRATIONS #####'
        block: |
          fzf --fish | source
          zoxide init fish | source
          abbr -a --position anywhere -- --help '--help | bat -plhelp'
          abbr -a --position anywhere -- -h '-h | bat -plhelp'

    - name: 👉 Обновление автодополнений для fish
      become: false
      become_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
      shell: |
        fish -c 'fish_update_completions'
        mkdir -p ~/.config/fish/completions
        procs --gen-completion-out fish > ~/.config/fish/completions/procs.fish

    - name: 👉 Обновление базы tldr
      become: false
      become_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
      shell: fish -c 'tldr --update'

    - name: 👉 Отключение KDE Wallet
      ini_file:
        path: "{{ ansible_env.HOME }}/.config/kwalletrc"
        create: yes
        section: Wallet
        option: Enabled
        value: 'false'
        mode: '0644'
      become: false
      become_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"

    - name: 👉 Переназначение горячих клавиш для Spectacle
      blockinfile:
        path: "{{ ansible_env.HOME }}/.config/kglobalshortcutsrc"
        marker: "##### {mark} SPECTACLE SHORTCUTS #####"
        block: |
          [services][org.kde.spectacle.desktop]
          RectangularRegionScreenShot=Print
          _launch=Meta+Shift+Print\tMeta+Shift+S

    - name: 👉 Копирование .config
      copy:
        src: "{{ playbook_dir }}/.config/"
        dest: "{{ ansible_env.HOME }}/.config/"
        mode: "0644"
        directory_mode: "0755"

    - name: 👉 Копирование .local
      copy:
        src: "{{ playbook_dir }}/.local/"
        dest: "{{ ansible_env.HOME }}/.local/"
        mode: "0644"
        directory_mode: "0755"

    - name: Информационное сообщение
      debug:
        msg: |
          ========================================================================
          ✅ Установка завершена!

          ℹ️ ВАЖНО: Чтобы изменения для Docker, NVIDIA, Julia и VirtualBox
          вступили в силу, необходимо перезагрузить компьютер.

          Для VirtualBox может понадобиться:
          sudo modprobe vboxdrv
          ========================================================================
